include:
  - ./ops/dev/observability/docker-compose.yml

x-dotnet_sync: &dotnet_sync
  develop:
    watch:
      - action: sync
        path: ./src/
        target: ./src/

x-node_base: &node_base
  build:
    context: ./src/
    dockerfile: ./Raft_Node/Dockerfile
    target: development
  <<: *dotnet_sync

x-node-environment: &node-environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ApiOptions__NodeCount: 3
  ApiOptions__NodeServiceName: raftnode
  ApiOptions__NodeServicePort: 8080
  ApiOptions__LogMessageIntervalSeconds: 30
  TZ: America/Denver

services:
  nginx:
    depends_on:
      - asteroid-client
    build:
      context: ./ops/dev/
      dockerfile: nginx.Dockerfile
    ports:
      - "3001:80"
    develop:
      watch:
        - action: sync+restart
          path: ./ops/dev/nginx.conf
          target: /etc/nginx/conf.d/default.conf

  realtime:
    build:
      context: ./src/
      dockerfile: ./RealTimeCommunication/Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__ServiceName: "Websockets"
      ObservabilityOptions__CollectorUrl: http://collector:4317
      DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
      TZ: America/Denver
    <<: *dotnet_sync

  asteroid-client:
    build:
      context: ./src/
      dockerfile: ./Asteroids/Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SignalREnv__ActorHubUrl: http://nginx:80/ws/actorhub
      ObservabilityOptions__CollectorUrl: http://collector:4317
      ObservabilityOptions__ServiceName: "AsteroidClient"
      DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
      TZ: America/Denver
    <<: *dotnet_sync

  gateway:
    build:
      context: ./src/
      dockerfile: ./Raft_Gateway/Dockerfile
      target: development
    environment:
      ApiOptions__NodeCount: 3
      ApiOptions__NodeServiceName: gateway
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__ServiceName: "gateway"
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    <<: *dotnet_sync

  raftnode1:
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 1
      ObservabilityOptions__ServiceName: Node1

  raftnode2:
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 2
      ObservabilityOptions__ServiceName: Node2

  raftnode3:
    <<: *node_base
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 3
      ObservabilityOptions__ServiceName: Node3
