include:
  - ./ops/dev/observability/docker-compose.yml
  # - ./ops/dev/raft/docker-compose.yml

x-dotnet_sync: &dotnet_sync
  develop:
    watch:
      - action: sync
        path: ./src/
        target: ./src/

x-akka_actor_env: &akka_actor_env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  SignalREnv__AccountHubUrl: http://realtime:8080/accountHub
  SignalREnv__LobbyHubUrl: http://realtime:8080/lobbyHub
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ObservabilityOptions__ServiceName: "AsteroidClient"
  ActorOptions__ActorSeeds: "akka.tcp://AsteroidSystem@lighthouse:4053"
  DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
  TZ: America/Denver

x-akka_actor_base: &akka_actor_base
  build:
    context: ./src/
    dockerfile: ./Raft_Gateway/Dockerfile
    target: development
  <<: *dotnet_sync

services:

  lighthouse:
    # https://github.com/petabridge/lighthouse
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - "9110:9110"
    environment:
      ACTORSYSTEM: "AsteroidSystem"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://AsteroidSystem@lighthouse:4053"
    restart: unless-stopped

  nginx:
    depends_on:
      - asteroid-client
      - grafana
    build:
      context: ./ops/dev/
      dockerfile: nginx.Dockerfile
    ports:
      - "3001:80"
    develop:
      watch:
        - action: sync+restart
          path: ./ops/dev/nginx.conf
          target: /etc/nginx/conf.d/default.conf

  realtime:
    build:
      context: ./src/
      dockerfile: ./RealTimeCommunication/Dockerfile
      target: development
    environment:
      ActorOptions__ActorRoles: "SignalR"
      AcotirOptions__ActorHostName: "realtime"
      <<: *akka_actor_env
    <<: *akka_actor_base

  asteroid-client:
    build:
      context: ./src/
      dockerfile: ./Asteroids/Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SignalREnv__AccountHubUrl: http://realtime:8080/accountHub
      SignalREnv__LobbyHubUrl: http://realtime:8080/lobbyHub
      ObservabilityOptions__CollectorUrl: http://collector:4317
      ObservabilityOptions__ServiceName: "AsteroidClient"
      DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
      TZ: America/Denver
    <<: *dotnet_sync

  gateway:
    build:
      context: ./src/
      dockerfile: ./Raft_Gateway/Dockerfile
      target: development
    environment:
      ApiOptions__NodeCount: 3
      ApiOptions__NodeServiceName: gateway
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__ServiceName: "gateway"
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    <<: *dotnet_sync
