x-node_base: &node_base
  build:
    context: ./../../src/
    dockerfile: ./Raft_Node/Dockerfile
  networks:
    - GD_Network

x-node-environment: &node-environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://GD_collector:4317
  ApiOptions__NodeCount: 3
  ApiOptions__NodeServiceName: raftnode
  ApiOptions__NodeServicePort: 8080
  ApiOptions__LogMessageIntervalSeconds: 30
  TZ: America/Denver

services:
  gateway:
    build:
      context: ./../../src/
      dockerfile: ./Raft_Gateway/Dockerfile
    container_name: GD_Gateway
    environment:
      ApiOptions__NodeCount: 3
      ApiOptions__NodeServiceName: gateway
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__ServiceName: "gateway"
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    networks:
      - GD_Network

  raftnode1:
    <<: *node_base
    container_name: GD_RaftNode1
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 1
      ObservabilityOptions__ServiceName: Node1

  raftnode2:
    <<: *node_base
    container_name: GD_RaftNode2
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 2
      ObservabilityOptions__ServiceName: Node2

  raftnode3:
    <<: *node_base
    container_name: GD_RaftNode3
    environment:
      <<: *node-environment
      ApiOptions__NodeIdentifier: 3
      ObservabilityOptions__ServiceName: Node3
