include:
  - compose.observability.yml
  - compose.raft.yml

x-akka_actor_env: &akka_actor_env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  ObservabilityOptions__ServiceName: "AsteroidActorSystem"
  RaftConnectionOptions__GatewayUrl: http://gateway:8080
  ActorOptions__ActorSeeds: "akka.tcp://Asteroids@lighthouse:4053"
  DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
  TZ: America/Denver

x-akka_actor_base: &akka_actor_base
  build:
    context: ./../../src/
    dockerfile: ./RealTimeCommunication/Dockerfile
    target: development

x-asteroid_client_env: &asteroid_client_env
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  SignalREnv__AccountHubUrl: http://realtime:8080/accountHub
  SignalREnv__LobbyHubUrl: http://realtime:8080/lobbyHub
  SignalREnv__ErrorHubUrl: http://realtime:8080/errorHub
  ObservabilityOptions__CollectorUrl: http://collector:4317
  DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
  TZ: America/Denver

x-asteroid_client_base: &asteroid_client_base
  build:
    context: ./../../src/
    dockerfile: ./Asteroids/Dockerfile

services:

  nginx:
    container_name: GD_asteroids_swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=drewdroids.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/garrett/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:4325:443
    restart: unless-stopped

  realtime:
    container_name: GD_asteroids_realtime
    environment:
      ActorOptions__ActorRoles: "SignalR"
      ActorOptions__ActorHostName: "realtime"
      <<: *akka_actor_env
    <<: *akka_actor_base

  actor-node-1:
    container_name: GD_Akka_Node_1
    environment:
      ActorOptions__ActorRoles: "Lobbies"
      ActorOptions__ActorHostName: "actor-node-1"
      <<: *akka_actor_env
    <<: *akka_actor_base

  actor-node-2:
    container_name: GD_Akka_Node_2
    environment:
      ActorOptions__ActorRoles: "Lobbies"
      ActorOptions__ActorHostName: "actor-node-2"
      <<: *akka_actor_env
    <<: *akka_actor_base

  asteroid-client-1:
    container_name: GD_Client_1
    <<: *asteroid_client_base
    environment:
      <<: *asteroid_client_env
      ObservabilityOptions__ServiceName: "AsteroidClient1"

  asteroid-client-2:
    container_name: GD_Client_2
    <<: *asteroid_client_base
    environment:
      <<: *asteroid_client_env
      ObservabilityOptions__ServiceName: "AsteroidClient2"
