include:
  - compose.observability.yml
  - compose.raft.yml

services:

  nginx:
    container_name: GD_asteroids_swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=drewdroids.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/garrett/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:4325:443
    restart: unless-stopped

  realtime:
    container_name: GD_asteroids_realtime
    build:
      context: ./../../src/
      dockerfile: ./RealTimeCommunication/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__ServiceName: "Websockets"
      ObservabilityOptions__CollectorUrl: http://collector:4317
      RaftConnectionOptions__GatewayUrl: http://gateway:8080
      DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
      TZ: America/Denver

  asteroid-client:
    container_name: GD_asteroids_client
    build:
      context: ./../../src/
      dockerfile: ./Asteroids/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SignalREnv__AccountHubUrl: https://nginx:80/accountHub
      SignalREnv__LobbyHubUrl: https://nginx:80/lobbyHub
      ObservabilityOptions__CollectorUrl: http://collector:4317
      ObservabilityOptions__ServiceName: "AsteroidClient"
      DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH: 1
      TZ: America/Denver
