name: Deploy

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}


on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/format.yml

  # tests:
  #   needs: format
  #   uses: ./.github/workflows/tests.yml

  deploy-application:
    needs: format
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: redeploy application
        run: |
          cd ops/prod
          docker compose pull
          docker compose down --remove-orphans
          docker compose up -d --build
